Dev branch PR for code review to merge into main
theshivamverma/e-commerce-backend pull request #1
Opened 2021-05-04 06:06 UTC by theshivamverma

2021-05-08 10:35 UTC, h-harsh requested changes

2021-05-08 10:35 UTC, h-harsh commented on index.js
> +
You can put a route for error handleing

2021-05-08 10:35 UTC, h-harsh commented on routes/cart.route.js
> +    res.json({ success: false, message: "error retrieving carts data" });
Try giving status codes for error

2021-05-08 10:35 UTC, h-harsh commented on routes/cart.route.js
> +      res.status(400).jsn({ success: false, message: "error retrieving cart" });
correct spelling of JSON

2021-05-08 10:35 UTC, h-harsh commented on routes/cart.route.js
> +                 console.log(err);
Remove  console statements from code

2021-05-08 10:35 UTC, h-harsh commented on routes/cart.route.js
> +  // });
remove unused code

2021-05-08 10:35 UTC, h-harsh commented on routes/product.route.js
> +        .status(500)
check status code for this error

2021-05-10 14:42 UTC, WhoAdarshPandya commented on index.js
> +const bodyParser = require("body-parser");
we can now use express's body parser

```
app.use(express.json())
```

2021-05-10 14:42 UTC, WhoAdarshPandya commented on routes/cart.route.js
> +        if(cartItem.product._id == prodId){
`===` convention

2021-05-10 14:42 UTC, adarshwritescode commented on routes/product.route.js
> +}
you can comment it out if this is of no use

2021-05-10 14:42 UTC, adarshwritescode commented on routes/user.route.js
> +      const user = req.body;
sanitizing body before storing would be great :)

you can trim whitespaces around and convert it to lower case

2021-11-20 12:32 UTC, merged